<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>yunqi.zhibei</groupId>
        <artifactId>steward-parent</artifactId>
        <version>0.1.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>steward-bom</artifactId>
    <packaging>pom</packaging>
    <name>Yunqi Steward BOM</name>

    <dependencyManagement>
        <dependencies>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-telemetry-core</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-control-configuration-management-core</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-control-configuration-management-file-properties</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-control-resource-management-core</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-control-resource-management-refresh</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-control-resource-management-restart</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-telemetry-metric-management-micrometer</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-telemetry-profile-management-jfr</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-telemetry-trace-management-opentelemetry</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-telemetry-log-management-slf4j</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-binding-testkit</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-configuration-source-testkit</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-control-configuration-management-nacos-v3</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-redis-library-client-jedis-v5</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-redis-library-client-jedis-v7</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-redis-library-client-lettuce-v6</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-redis-library-client-redisson-v4</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-redis-framework-client-spring-framework-v6-jedis-v7</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-mysql-library-client-connectorj-v9</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-mysql-library-client-mariadb-v3</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-postgresql-library-client-jdbc-v42</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-clickhouse-library-client-jdbc-v0</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-elasticsearch-library-client-java-v9</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-minio-library-client-java-v8</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-nacos-library-client-nacos-client-v3</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-neo4j-library-client-driver-v6</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-etcd-library-client-jetcd-v0</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-zookeeper-library-client-curator-v5</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-milvus-library-client-sdk-v2</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-elasticjob-library-client-lite-v3</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-rocketmq-library-client-rocketmq-client-v5</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-powerjob-library-client-worker-v5</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-xxljob-library-client-core-v2</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-seata-library-client-tm-v2</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-kafka-library-client-kafka-clients-v3</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-pulsar-library-client-pulsar-client-v3</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-rabbitmq-library-client-amqp-client-v5</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-mongodb-library-client-sync-v5</artifactId><version>${project.version}</version></dependency>
            <dependency><groupId>${project.groupId}</groupId><artifactId>steward-interaction-consul-library-client-api-v1</artifactId><version>${project.version}</version></dependency>
        </dependencies>
    </dependencyManagement>
</project>
